In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plts
import os

In [2]:
from dotenv import load_dotenv
load_dotenv()
CSV_PATH = os.getenv("CSV_PATH")
print(f"Caminho do arquivo CSV: {CSV_PATH}")

Caminho do arquivo CSV: /home/phaelzin/MD-PediatricHeart/data/raw/UCMF_raw.csv

In [3]:
df = pd.read_csv(CSV_PATH)
df.head()

,ID,Peso,Altura,IMC,Atendimento,DN,IDADE,Convenio,PULSOS,PA SISTOLICA,...,PPA,NORMAL X ANORMAL,B2,SOPRO,FC,HDA 1,HDA2,SEXO,MOTIVO1,MOTIVO2
0,1,5.0,51,19.0,11/05/06,30/03/06,0.12,GS,Normais,NaN,...,Não Calculado,Anormal,Normal,Sistólico,112,Palpitacao,NaN,M,6 - Suspeita de cardiopatia,6 - Palpitação/taquicardia/arritmia
1,2,3.5,50,14.0,25/05/05,19/05/05,0.02,GS,Normais,NaN,...,Não Calculado,Anormal,Normal,ausente,128,Dispneia,NaN,M,6 - Suspeita de cardiopatia,6 - Dispnéia
2,3,0.0,0,NaN,12/06/01,08/05/05,-4.05,SULA,Normais,NaN,...,Não Calculado,Anormal,Normal,Sistólico,88,Assintomático,NaN,M,2 - Check-up,NaN
3,4,8.1,65,19.0,15/10/09,21/04/09,0.50,NaN,Normais,NaN,...,Não Calculado,Anormal,Normal,ausente,92,Assintomático,NaN,M,5 - Parecer cardiológico,NaN
4,7,40.0,151,18.0,14/01/08,14/08/95,12.89,SAME,Normais,NaN,...,Não Calculado,Anormal,Normal,ausente,96,Dor precordial,NaN,M,5 - Parecer cardiológico,NaN

### Volume dos dados

In [ ]:
# Dimensões do dataset
print("Número de linhas (objetos):", df.shape[0])
print("Número de colunas (atributos):", df.shape[1])

Número de linhas (objetos): 12873
Número de colunas (atributos): 21

## Análise exploratória dos dados

### Detecção de dados faltantes

In [ ]:
def missing_data_report(df):
    missing = df.isnull().sum()
    percent = (missing / len(df)) * 100
    report = pd.DataFrame({'Missing Values': missing, 'Percent (%)': percent})
    return report

# Exemplo de uso:
missing_data_report(df)

                  Missing Values  Percent (%)
ID                             0     0.000000
Peso                         318     2.470287
Altura                         0     0.000000
IMC                         4727    36.720267
Atendimento                  983     7.636138
DN                          1376    10.689039
IDADE                       1496    11.621223
Convenio                    4108    31.911753
PULSOS                      1194     9.275227
PA SISTOLICA                7730    60.048163
PA DIASTOLICA               7740    60.125845
PPA                          217     1.685699
NORMAL X ANORMAL            1168     9.073254
B2                          1178     9.150936
SOPRO                       1167     9.065486
FC                          1868    14.510992
HDA 1                       4270    33.170201
HDA2                       12466    96.838344
SEXO                           4     0.031073
MOTIVO1                     1055     8.195448
MOTIVO2                     3496    27.157617